from __future__ import annotations

import argparse
import hashlib
import json
import re
import secrets
import string
from dataclasses import dataclass
from pathlib import Path
from xml.sax.saxutils import escape as xml_escape

DEFAULT_SSID = "PedFlowSensor"
DEFAULT_PASSWORD_LENGTH = 20
PASSWORD_ALPHABET = string.ascii_letters + string.digits
WPA2_PASSWORD_MIN_LENGTH = 8
WPA2_PASSWORD_MAX_LENGTH = 63
GENERATED_NOTICE = "Auto-generated by scripts/generate_secrets.py. Do not commit this file."
MAX_WIFI_PROFILE_STEM_LENGTH = 80
TRUNCATION_DIGEST_LENGTH = 10


@dataclass(frozen=True)
class WifiSecrets:
    ssid: str
    password: str


@dataclass(frozen=True)
class SecretPaths:
    source_json: Path
    firmware_header: Path
    laptop_env: Path
    laptop_text: Path
    windows_wifi_profile: Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate local PedFlow Wi-Fi secrets for firmware and laptop setup."
    )
    parser.add_argument(
        "--project-root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="Project root containing GroveAIV2_Box_AP and the secrets directory.",
    )
    parser.add_argument("--ssid", help="Wi-Fi access point SSID to store in the local secrets.")
    parser.add_argument(
        "--password",
        help=(
            "Explicit WPA2 password. If omitted, the existing local password is reused or a "
            "new one is generated."
        ),
    )
    parser.add_argument(
        "--password-length",
        type=int,
        default=DEFAULT_PASSWORD_LENGTH,
        help="Length for generated passwords.",
    )
    parser.add_argument(
        "--rotate",
        action="store_true",
        help="Generate a new password even when a local password already exists.",
    )
    return parser.parse_args()


def generated_password(length: int = DEFAULT_PASSWORD_LENGTH) -> str:
    if length < WPA2_PASSWORD_MIN_LENGTH or length > WPA2_PASSWORD_MAX_LENGTH:
        raise ValueError(
            f"Generated WPA2 passwords must be {WPA2_PASSWORD_MIN_LENGTH}-"
            f"{WPA2_PASSWORD_MAX_LENGTH} characters."
        )
    return "".join(secrets.choice(PASSWORD_ALPHABET) for _ in range(length))


def validate_ssid(ssid: str) -> str:
    if not ssid:
        raise ValueError("Wi-Fi SSID must not be empty.")
    try:
        ssid_length = len(ssid.encode("utf-8"))
    except UnicodeEncodeError as exc:
        raise ValueError("Wi-Fi SSID must be valid UTF-8.") from exc
    if ssid_length > 32:
        raise ValueError("Wi-Fi SSID must be 32 bytes or shorter.")
    if any(ch in "\r\n" for ch in ssid):
        raise ValueError("Wi-Fi SSID must not contain line breaks.")
    return ssid


def validate_password(password: str) -> str:
    if len(password) < WPA2_PASSWORD_MIN_LENGTH or len(password) > WPA2_PASSWORD_MAX_LENGTH:
        raise ValueError(
            f"WPA2 password must be {WPA2_PASSWORD_MIN_LENGTH}-"
            f"{WPA2_PASSWORD_MAX_LENGTH} characters."
        )
    if any(ord(ch) < 32 or ord(ch) > 126 for ch in password):
        raise ValueError("WPA2 password must use printable ASCII characters.")
    return password


def slugify_ssid(ssid: str) -> str:
    slug = re.sub(r"[^A-Za-z0-9_.-]+", "_", ssid).strip("._-")
    return truncate_with_digest(slug or "pedflow", MAX_WIFI_PROFILE_STEM_LENGTH)


def truncate_with_digest(value: str, max_length: int) -> str:
    if len(value) <= max_length:
        return value
    digest = hashlib.sha256(value.encode("utf-8")).hexdigest()[:TRUNCATION_DIGEST_LENGTH]
    prefix_length = max_length - len(digest) - 1
    if prefix_length < 1:
        raise ValueError("max_length is too short for deterministic truncation")
    return f"{value[:prefix_length]}-{digest}"


def paths_for(project_root: Path, ssid: str = DEFAULT_SSID) -> SecretPaths:
    secret_dir = project_root / "secrets"
    profile_name = f"{slugify_ssid(ssid)}-wifi-profile.xml"
    return SecretPaths(
        source_json=secret_dir / "pedflow_wifi.json",
        firmware_header=project_root / "GroveAIV2_Box_AP" / "pedflow_secrets.h",
        laptop_env=secret_dir / "pedflow_wifi.env",
        laptop_text=secret_dir / "pedflow_wifi.txt",
        windows_wifi_profile=secret_dir / profile_name,
    )


def read_existing(source_json: Path) -> WifiSecrets | None:
    if not source_json.exists():
        return None
    with source_json.open(encoding="utf-8") as source_file:
        data = json.load(source_file)
    return WifiSecrets(
        ssid=validate_ssid(str(data["wifi_ap_ssid"])),
        password=validate_password(str(data["wifi_ap_password"])),
    )


def resolve_secrets(args: argparse.Namespace) -> WifiSecrets:
    existing = read_existing(paths_for(args.project_root).source_json)
    ssid = validate_ssid(args.ssid or (existing.ssid if existing else DEFAULT_SSID))

    if args.password:
        password = validate_password(args.password)
    elif args.rotate or existing is None:
        password = generated_password(args.password_length)
    else:
        password = existing.password

    return WifiSecrets(ssid=ssid, password=password)


def cpp_string(value: str) -> str:
    replacements = {
        "\\": "\\\\",
        '"': '\\"',
        "\n": "\\n",
        "\r": "\\r",
        "\t": "\\t",
    }
    escaped = "".join(replacements.get(ch, ch) for ch in value)
    return f'"{escaped}"'


def env_value(value: str) -> str:
    if re.fullmatch(r"[A-Za-z0-9_.:@%+=,/-]+", value):
        return value
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def write_source_json(path: Path, wifi: WifiSecrets) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    data = {
        "_comment": GENERATED_NOTICE,
        "wifi_ap_ssid": wifi.ssid,
        "wifi_ap_password": wifi.password,
    }
    with path.open("w", encoding="utf-8", newline="\n") as output:
        json.dump(data, output, indent=2)
        output.write("\n")


def write_firmware_header(path: Path, wifi: WifiSecrets) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "\n".join(
            [
                "#pragma once",
                "",
                f"// {GENERATED_NOTICE}",
                f"constexpr const char PEDFLOW_WIFI_AP_SSID[] = {cpp_string(wifi.ssid)};",
                f"constexpr const char PEDFLOW_WIFI_AP_PASSWORD[] = {cpp_string(wifi.password)};",
                "",
            ]
        ),
        encoding="utf-8",
        newline="\n",
    )


def write_laptop_env(path: Path, wifi: WifiSecrets) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "\n".join(
            [
                f"# {GENERATED_NOTICE}",
                f"PEDFLOW_WIFI_AP_SSID={env_value(wifi.ssid)}",
                f"PEDFLOW_WIFI_AP_PASSWORD={env_value(wifi.password)}",
                "",
            ]
        ),
        encoding="utf-8",
        newline="\n",
    )


def write_laptop_text(path: Path, wifi: WifiSecrets) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "\n".join(
            [
                GENERATED_NOTICE,
                "",
                f"SSID: {wifi.ssid}",
                f"Password: {wifi.password}",
                "",
            ]
        ),
        encoding="utf-8",
        newline="\n",
    )


def write_windows_wifi_profile(path: Path, wifi: WifiSecrets) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    ssid = xml_escape(wifi.ssid)
    password = xml_escape(wifi.password)
    path.write_text(
        "\n".join(
            [
                '<?xml version="1.0"?>',
                '<WLANProfile xmlns="http://www.microsoft.com/networking/WLAN/profile/v1">',
                f"  <name>{ssid}</name>",
                "  <SSIDConfig>",
                "    <SSID>",
                f"      <name>{ssid}</name>",
                "    </SSID>",
                "  </SSIDConfig>",
                "  <connectionType>ESS</connectionType>",
                "  <connectionMode>manual</connectionMode>",
                "  <MSM>",
                "    <security>",
                "      <authEncryption>",
                "        <authentication>WPA2PSK</authentication>",
                "        <encryption>AES</encryption>",
                "        <useOneX>false</useOneX>",
                "      </authEncryption>",
                "      <sharedKey>",
                "        <keyType>passPhrase</keyType>",
                "        <protected>false</protected>",
                f"        <keyMaterial>{password}</keyMaterial>",
                "      </sharedKey>",
                "    </security>",
                "  </MSM>",
                "</WLANProfile>",
                "",
            ]
        ),
        encoding="utf-8",
        newline="\n",
    )


def write_all(project_root: Path, wifi: WifiSecrets) -> SecretPaths:
    output_paths = paths_for(project_root, wifi.ssid)
    write_source_json(output_paths.source_json, wifi)
    write_firmware_header(output_paths.firmware_header, wifi)
    write_laptop_env(output_paths.laptop_env, wifi)
    write_laptop_text(output_paths.laptop_text, wifi)
    write_windows_wifi_profile(output_paths.windows_wifi_profile, wifi)
    return output_paths


def main() -> int:
    args = parse_args()
    project_root = args.project_root.resolve()
    wifi = resolve_secrets(args)
    output_paths = write_all(project_root, wifi)
    print(f"Generated local Wi-Fi secrets for SSID {wifi.ssid!r}.")
    print(f"Firmware header: {output_paths.firmware_header}")
    print(f"Laptop credentials: {output_paths.laptop_text}")
    print(f"Windows Wi-Fi profile: {output_paths.windows_wifi_profile}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
